### ISSUE TITLE
`Tabs` component uses fixed `z-index`

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/cypress-design#249]
`Tabs` component buttons have `z-20` class applied which can elevate the component above an overlay. Can this be restructured to rely on `auto` strategy for `z-index`?

<img width="1105" alt="242649932-7ff396e3-f9df-40d4-98ff-96f45fee8299" src="https://github.com/cypress-io/cypress-design/assets/11482842/16bacdfb-95d0-4a61-95c1-98ba04e2ce6f">

Able to work around it in the app by applying these overrides - as a simple solution it looks like you can bump the `z-index` values from 10, 20, 30 to 1, 2, 3 to reduce the risk of overlap conflict

```scss
button[role="tab"] {
    z-index: 2;
}
div {
  &:first-of-type {
    z-index: 1;
  }
  &:last-of-type {
    z-index: 3;
  }
}
```
