### ISSUE TITLE
Fix the Buttons styles for links

### ISSUE THREAD

**Issue by ryanjwilke** [cypress-io/cypress-design#278]
This was discovered [in this thread on Slack](https://cypressio.slack.com/archives/C3WD9SGKW/p1689363888152069).

![image](https://github.com/cypress-io/cypress-design/assets/211597/9fcd4c6a-b516-4b37-8a6e-da2ae5b4fb81)

**Comment by elevatebart** [comment]
What code could have triggered this? 

@pstakoun can you please provide a link to a repro. The blue foreground is part of the button styles. The purple background is absolutely not. We could imagine, if it becomes a design system standard, a purple version of the button. 

If it is not meant to become the standard focus behavior, I suggest we use a link `<a href="url">Submit Feedback</a>`.

**Comment by pstakoun** [comment]
@elevatebart this is a design system component used out of the box:

```
    <Button
      data-cy="feedback-button"
      href={`${url}?${qs}`}
      target="_blank"
      variant="purple-dark"
      className={styles.feedbackButton}
    >
      Submit feedback
    </Button>
```

```
.feedbackButton {
  display: inline-flex;
  font-size: 14px;
  line-height: 20px;
  font-weight: 500;
  padding: 6px 12px;

  &:hover,
  &:focus {
    color: $gray-A1;
    text-decoration: none;
  }
}
```

**Comment by elevatebart** [comment]
Out of the box...

```css
.feedbackButton {
  display: inline-flex;
  font-size: 14px;
  line-height: 20px;
  font-weight: 500;
  padding: 6px 12px;

  &:hover,
  &:focus {
    color: $gray-A1;
    text-decoration: none;
  }
}
```
